name: BlogList Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  CONDITION: ${{ contains(join(github.event.commits.*.message, ','), '#skip') }}

jobs:
  run_environment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.workflow_run.head_commit) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.workflow_run.head_commit.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: Condition resolution
        run: echo ${{ env.CONDITION }}
  blogs_deploy_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Backend dependencies
        run: cd BlogListApp && npm install
      - name: Check Backend Linting
        run: cd BlogListApp && npm run lint
      - name: Backend Unit Tests
        run: cd BlogListApp && npm run test:back
      - name: Install Frontend dependencies
        run: cd BlogListFront && npm install
      - name: Check Frontend Linting
        run: cd BlogListFront && npm run lint
      - name: Frontend Unit Tests
        run: cd BlogListFront && npm run test:front
      - name: Frontend e2e tests
        uses: cypress-io/github-action@v6
        with:
          project: ./BlogListFront
          browser: chrome
          command: npm run test:e2e
          start: |
            npm run start
            cd ../BlogListApp && npm run start:test
          wait-on: http://localhost:3003

  version_numbering:
    needs: [blogs_deploy_pipeline]
    if: ${{ (github.ref_name == 'main') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
      - name: Bump version and push tag
        if: ${{ env.CONDITION == 'false' }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
      - name: Skipping version
        if: ${{ env.CONDITION == 'true' }}
        run: echo ${{ toJson(github.event.repository.commits_url) }} skipped
